name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ./setup.sh
      run: docker run --rm --volume=`pwd`:/home/mykiwi mykiwi/manjaro bash -c 'pwd; ls -la; ./setup.sh'
      
