name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: initialize manjaro
      run: |
        chmod 777 setup.sh
        cd .github/workflows
        docker build -t manjaro .
    - name: ./setup.sh
      run: docker run --rm --volume=`pwd`:/home/mykiwi manjaro sh -c 'pwd; ls -la; ./setup.sh'
      
