name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: initialize manjaro
      run: |
        cd .github/workflows
        docker build -t manjaro .
    - name: ./setup.sh
      run: docker run --rm -v `pwd`:`pwd` -w `pwd` manjaro ./setup.sh
